name: DeepACSA_new
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=21.0.1
  - pip:
    - jupyter==1.0.0
    - Keras==2.9.0
    - matplotlib==3.5.2
    - numpy==1.21.2
    - opencv-contrib-python==4.5.3.56
    - pandas==1.3.3
    - Pillow==8.3.2
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - tensorflow==2.9.0
    - tqdm==4.62.3
    - openpyxl==3.0.9
    - h5py==3.4.0
